# Generated by Django 6.0.6 on 2026-06-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_servicio',
            field=models.BooleanField(default=False),
        ),
    ]
