# Generated by Django 6.0.6 on 2026-06-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_itemventa_producto_alter_venta_tienda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
