# Generated by Django 6.0.6 on 2026-06-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
