# Generated by Django 6.0.6 on 2026-06-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_itemventa_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
