# Generated by Django 6.0.6 on 2026-06-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_venta_cancelada'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
    ]
