# Generated by Django 6.0.6 on 2026-06-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_cerrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
