# Generated by Django 6.0.6 on 2026-06-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventa',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
