# Generated by Django 6.0.6 on 2026-07-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_itemventa_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='mesa',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='pago',
            field=models.CharField(default='efectivo', max_length=20),
        ),
    ]
